[package]
name = "rust-template"
version = "0.1.0"
authors = ["flip1995 <hello@philkrones.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
